#!/usr/bin/env escript
%%! -sname dronex_sine_table
%%
%% Print the sine table `fixed.erl' carries, so a checked-in constant is
%% reproducible rather than magic.
%%
%% ⚠ WHY A TABLE AT ALL. design/DESIGN_THE_AIRSPACE.md requires a fight to be a
%% pure function of its start state, byte for byte, on any machine. `math:sin/1'
%% is libm and libm is not promised to agree across libc versions, so one call on
%% the match path would make a published raid unverifiable by the island that
%% flew it. The table is computed ONCE, here, offline, and checked in.
%%
%% ⚠⚠ AND THAT IS WHY THIS SCRIPT IS NOT WIRED INTO THE BUILD. Generating the
%% table at compile time would put libm back on the path by the back door: two
%% machines building the same commit could produce different tables and nothing
%% would say so. The output is checked in, and this script exists so a reader can
%% verify it rather than trust it.
%%
%% Usage:
%%   scripts/generate_sine_table.escript            print the table
%%   scripts/generate_sine_table.escript --verify   compare against fixed.erl

-define(ENTRIES, 256).
-define(SCALE, 32768).

main(["--verify"]) -> verify();
main([]) -> io:put_chars(rendered());
main(_) -> io:format("usage: generate_sine_table.escript [--verify]~n"), halt(2).

%% One entry per binary angle. 256 units is a full turn, so entry I is
%% sin(2*pi*I/256) scaled by 32768 and rounded to nearest.
table() ->
    [round(math:sin(2 * math:pi() * I / ?ENTRIES) * ?SCALE)
     || I <- lists:seq(0, ?ENTRIES - 1)].

rendered() ->
    Rows = rows(table(), []),
    ["%% GENERATED by scripts/generate_sine_table.escript. Do not hand-edit.\n"
     "%% sin(2*pi*I/256) * 32768, rounded. Verify with `--verify'.\n"
     "-define(SIN_TABLE, {\n",
     lists:join(",\n", [["    ", lists:join(", ", [integer_to_list(N) || N <- R])]
                        || R <- Rows]),
     "\n}).\n"].

rows([], Acc) -> lists:reverse(Acc);
rows(L, Acc) when length(L) =< 8 -> lists:reverse([L | Acc]);
rows(L, Acc) ->
    {Row, Rest} = lists:split(8, L),
    rows(Rest, [Row | Acc]).

%% Reads the numbers back out of the header and compares. A mismatch names the
%% first index that differs, because "the table is wrong" is not actionable.
verify() ->
    Path = filename:join([filename:dirname(escript:script_name()), "..",
                          "apps", "hecate_dronex", "include", "sine_table.hrl"]),
    {ok, Bin} = file:read_file(Path),
    %% ⚠ COMMENT LINES ARE DROPPED FIRST. The header's own second line reads
    %% "* 32768", and the first version of this check scraped that as a 257th
    %% entry and reported a length mismatch against a table that was correct.
    Body = [L || L <- string:split(binary_to_list(Bin), "\n", all),
                 string:prefix(string:trim(L), "%%") =:= nomatch],
    Found = [list_to_integer(S)
             || S <- string:lexemes(lists:flatten(lists:join("\n", Body)),
                                    " \n,{}()"),
                is_number_string(S)],
    compare(Found, table(), 0).

is_number_string([$- | T]) -> is_number_string(T);
is_number_string([]) -> false;
is_number_string(S) -> lists:all(fun (C) -> C >= $0 andalso C =< $9 end, S).

compare(Found, Want, _I) when length(Found) =/= length(Want) ->
    io:format("MISMATCH: header holds ~p entries, want ~p~n",
              [length(Found), length(Want)]),
    halt(1);
compare([], [], _I) ->
    io:format("The checked-in table matches: 256 entries, scale 32768.~n"),
    halt(0);
compare([A | _], [B | _], I) when A =/= B ->
    io:format("MISMATCH at index ~p: header ~p, computed ~p~n", [I, A, B]),
    halt(1);
compare([_ | As], [_ | Bs], I) ->
    compare(As, Bs, I + 1).
